### PR TITLE
Fix/mspec params

### PR DESCRIPTION
**Pull request by GregOnNet**
Hi,

I recognized an error when passing more then one `*.dll` to the mspec task.

``` javascript
mspec: {
  specs: {
    src: ['src/Project.Web/bin/*Specs.dll']
  },
  options: {
    toolsPath: 'src/packages/Machine.Specifications.0.7.0/tools',
    output: 'reports/mspec'
  }
}
```

image

At first it looks like that two assemblies could not be found.Certainly the mapping of the given `*.dlls` is treated as one concatenated string.

image

This leads into a wrong argument string for mspec.

``` cmd
.. mspec-clr4.exe [options] -t "src/FirstSpec.dll,src/SecondSpec.dll"
```

It should be:

``` cmd
.. mspec-clr4.exe [options] -t "src/FirstSpec.dll"  "src/SecondSpec.dll"
```

**What I have done**
- I fixed this issue by passing the src-parameter of the files object. 23d04b9
- I also added some specs to test the argument creation for mspec.
- For better testing I moved the `buildCommand`-Function into an own module called `mspec.command`.

Can you please check my modifications? You may want to update the npm-package.

Thanks in advance
Gregor

### CODE REVIEW

**Comment by marcofranssen** [comment]
Thanks for the modifications. Will have a look at it ASAP. Just returned
from a long holiday. Sorry for the late response.

2014-09-11 14:47 GMT+02:00 Gregor Woiwode notifications@github.com:

**Comment by GregOnNet** [comment]
Hi Marco,

did you have time to analize my changes.
I also can provide further information if needed.

Thanks
Gregor

**Comment by marcofranssen** [comment]
Hi Greg,

Sorry for the huge delay. Last year has been a very busy year for me.

I tried to merge it but had some conflicts... On this branch you can see the result GregOnNet-fix/mspec-params

One of the tests is failing. Could you have a look how to get that fixed?

As soon you have a fix I can merge it in and publish a new version on npm.

**Comment by GregOnNet** [comment]
Hi Marco,

thanks for your reply.

The conflict is because of the last merge of the pull-request provided by @Wolfium.
I will try to merge these changes.

I wish you a happy new year :smiley: 
Gregor

**Comment by dabperceptive** [comment]
:+1: 

i have the same issue and it would be great if you can merge this fix and publish a new version.

**Comment by GregOnNet** [comment]
Hey guys,

sorry, I had no possibility in the last few weeks to make this job.
I look forward to manage this next week.

**Comment by GregOnNet** [comment]
I added a fix that works with the current version.
I will open another pull request because I worked in another branch.

Cheers
Gregor

**Pull request closed without merging**
