### PR TITLE
Fixed issue with spaces where in path

### PR DESCRIPTION
**Pull request by Wolfium**
Removed any manual handling of any quote in paths, in order to fix issue when space included in the any path under windows.

Added test to probe it works with spaces in path with same files.

### CODE REVIEW

**Comment by Wolfium** [comment]
Hi @marcofranssen, would you be able to merge and if possible could you push updated version into NPM if it works?

Thanks in advance...
Regards

**Comment by marcofranssen** [comment]
Please resubmit the pull request with only the required code changes. There is a lot of spacing etc. changed.

**Comment by Wolfium** [comment]
I see, I guess that VS or Notepad++ made some assumptions... :8ball: 

Amended, let me know if it does it look better know? 

Again thanks @marcofranssen in advance for following up...
Regards

**Comment by Wolfium** [comment]
Hi @marcofranssen, sorry to be bothering you.

I already resubmited the requested changes within this same pull request.
Differences now are only code lines changed respecting spaces indentantions

Thanks in advance.

**Comment by Wolfium** [comment]
Hi, @marcofranssen, would it be possible to merge changes as requested.

Thanks in advance.
Regards
Wolfium

**Comment by Wolfium** [comment]
Great, thanks

**Pull request merged**
